version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
  app:
    image: node:18-alpine
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    working_dir: /app